sudo: required
dist: trusty

language: python

services:
  - docker

env:
  global:
      - DOCKER_VERSION=1.12.2-0~trusty
      - DOCKER_COMPOSE_VERSION=1.8.0
  matrix:
    - TOX_ENV=py27-django18-pil
    - TOX_ENV=py27-django18-imagemagick
    - TOX_ENV=py27-django18-graphicsmagick
    - TOX_ENV=py27-django18-redis
    - TOX_ENV=py27-django18-sentinel
    - TOX_ENV=py27-django18-wand
    - TOX_ENV=py27-django18-pgmagick
    - TOX_ENV=py27-django18-dbm
    - TOX_ENV=py34-django18-pil
    - TOX_ENV=py34-django18-imagemagick
    - TOX_ENV=py34-django18-graphicsmagick
    - TOX_ENV=py34-django18-redis
    - TOX_ENV=py34-django18-sentinel
    - TOX_ENV=py34-django18-wand
    - TOX_ENV=py34-django18-dbm
    - TOX_ENV=py34-django19-pil
    - TOX_ENV=py34-django19-imagemagick
    - TOX_ENV=py34-django19-graphicsmagick
    - TOX_ENV=py34-django19-redis
    - TOX_ENV=py34-django19-sentinel
    - TOX_ENV=py34-django19-wand
    - TOX_ENV=py34-django19-dbm
    - TOX_ENV=py34-django110-pil
    - TOX_ENV=py34-django110-imagemagick
    - TOX_ENV=py34-django110-graphicsmagick
    - TOX_ENV=py34-django110-redis
    - TOX_ENV=py34-django110-sentinel
    - TOX_ENV=py34-django110-wand
    - TOX_ENV=py34-django110-dbm

before_install:
  - apt-cache madison docker-engine
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}
  - sudo rm -f /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker-compose up --build -d

after_failure:
  - ./bash_cat_pip_log.sh

# after_success:
#  - coveralls

#install:
#  - pip install pip wheel
##  - pip install -q coveralls flake8 tox
#  - pip install -q flake8 tox

script:
  - env | sort
  - ./run_docker_single_test.sh

after_script:
  - docker-compose down


notifications:
  irc:
    channels:
      - "irc.freenode.org#sorl-thumbnail"
    on_success: change
    on_failure: change
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b368c47d69637f9a01a0
    on_success: change
    on_failure: change
    on_start: false     # default: false
